# Generated by Django 2.1 on 2018-08-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20180811_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialdisplaysettings',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
