# Generated by Django 2.1 on 2018-08-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_socialdisplaysettings_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialdisplaysettings',
            name='name',
            field=models.CharField(default='twitch', max_length=256),
        ),
    ]
