# Generated by Django 2.1 on 2018-08-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20180812_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='discord',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
