# Generated by Django 2.1 on 2018-08-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20180812_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialdisplaysettings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='user_profile.UserProfile'),
        ),
    ]
